version: "3.5"
services:
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    env_file:
      - ".env"
    volumes:
      - "./notebooks:/notebooks"
      - "./jupyter_data:/data"
    networks:
      - "local"

volumes:
  notebooks:

networks:
  local:
    name: "local"
    driver: "bridge"
